#!/bin/bash
# Autor:						Jensy Gregorio Gomez
# YouTube:						youtube.com/systech
# Instagram:					https://www.instagram.com/systech5/?hl=pt-br
# Github:						https://github.com/vaasystech-brz
# Data de criação:				01/01/2022
# Data de atualização:			01/01/2022
# Versão:						0.01
# Testado e homologado para a versão do Ubuntu Server 20.04.x LTS x64
#
# Configuração Global do Serviço de Rede do Grafana Server
#
# Configuração do usuário do Grafana Server
GRAFANA_USER=grafana
#
# Configuraçáo do grupo do Grafana Server
GRAFANA_GROUP=grafana
#
# Configuração do home do Grafana Server
GRAFANA_HOME=/usr/share/grafana
#
# Configuração do diretório de Log do Grafana Server
LOG_DIR=/var/log/grafana
#
# Configuração do diretório de Dados do Grafana Server
DATA_DIR=/var/lib/grafana
#
# Configuração do Número Máximo de Arquivos Abertos do Grafana Server
MAX_OPEN_FILES=10000
#
# Configuração do diretório de configuração do Grafana Server
CONF_DIR=/etc/grafana
#
# Arquivo de configuração inicial do Grafana Server
CONF_FILE=/etc/grafana/grafana.ini
#
# Reinicializar o serviço do Grafana Server após a atualização
RESTART_ON_UPGRADE=true
#
# Configuração do diretório de Plugins do Grafana Server
PLUGINS_DIR=/var/lib/grafana/plugins
#
# Configuração do diretório de Provisionamento do Grafana Server
PROVISIONING_CFG_DIR=/etc/grafana/provisioning
#
# Configuração do diretório do PID do Processo do Grafana Server
PID_FILE_DIR=/var/run/grafana
