#!/bin/bash
# Autor:						Jensy Gregorio Gomez
# YouTube:						youtube.com/systech
# Instagram:					https://www.instagram.com/systech5/?hl=pt-br
# Github:						https://github.com/vaasystech-brz
# Data de criação:				01/01/2022
# Data de atualização:			01/01/2022
# Versão:						0.01
# Testado e homologado para a versão do Ubuntu Server 20.04.x LTS x64
# Testado e homologado para a versão do OCS Inventory Server v2.9.x e Agent v2.9.x
#
# Agendamento do inventário do servidor utilizando o OCS Inventory Agent todo os dias as 12:00hs
# [minutos] [horas] [dias do mês] [mês] [dias da semana] [usuário] [comando]
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
0 12 * * * root /usr/local/bin/ocsinventory-agent --lazy > /dev/null 2>&1

# Obrigatório ter uma linha em branco no final do arquivo para que o agendamento funcione corretamente.

