#!/bin/bash
# Autor:						Jensy Gregorio Gomez
# YouTube:						youtube.com/systech
# Instagram:					https://www.instagram.com/systech5/?hl=pt-br
# Github:						https://github.com/vaasystech-brz
# Data de criação:				01/01/2022
# Data de atualização:			01/01/2022
# Versão:						0.01
# Testado e homologado para a versão do Ubuntu Server 20.04.x LTS x64
# Testado e homologado para a versão do OCS Inventory Server v2.9.x e Agent v2.9.x
#
# Configuração do Rotacionamento dos Logs do OCS Inventory Server, padrão manter 7 dias compactados
/var/log/ocsinventory-server/*.log {
	daily
	rotate 7
	compress
	delaycompress
	missingok
}
