#!/bin/bash
# Autor:						Jensy Gregorio Gomez
# YouTube:						youtube.com/systech
# Instagram:					https://www.instagram.com/systech5/?hl=pt-br
# Github:						https://github.com/vaasystech-brz
# Data de criação:				01/01/2022
# Data de atualização:			01/01/2022
# Versão:						0.01
# Testado e homologado para a versão do Ubuntu Server 20.04.x LTS x64
# Testado e homologado para a versão do Bind9 DNS Server v9.16.x
#
# Rotacionando os Logs das Estatísticas do RNDC Stats do Bind DNS Server utilizadas
# pelo sistema de monitoramento Netdata
/var/log/named/named.stats {
	daily
	rotate 4
	compress
	delaycompress
	create 0644 bind bind
	missingok
	postrotate
	rndc reload > /dev/null
	endscript
}