#!/bin/bash
# Autor:						Jensy Gregorio Gomez
# YouTube:						youtube.com/systech
# Instagram:					https://www.instagram.com/systech5/?hl=pt-br
# Github:						https://github.com/vaasystech-brz
# Data de criação:				01/01/2022
# Data de atualização:			01/01/2022
# Versão:						0.01
# Testado e homologado para a versão do Ubuntu Server 20.04.x LTS x64
# Testado e homologado para a versão do AWStats v7.x
#
# Desativando os envios de email do AWStats para o usuário root (padrão)
MAILTO=""

# Agendamento das atualização AWStats - estatísticas do Apache2, a cada 5 minutos, todos os dias
# do domínio: pti.intra, para adicionar novos domínio só acrescentar mais agendamentos nas linhas
# abaixo alterando somente a opção: -config
# [minutos] [horas] [dias do mês] [mês] [dias da semana] [usuário] [comando]
*/5 * * * * root /usr/lib/cgi-bin/awstats.pl -config=pti.intra -update > /dev/null

#Fim do agendamento, obrigatório ter uma linha no final para a execução correta.
