#!/bin/bash
# Autor:						Jensy Gregorio Gomez
# YouTube:						youtube.com/systech
# Instagram:					https://www.instagram.com/systech5/?hl=pt-br
# Github:						https://github.com/vaasystech-brz
# Data de criação:				01/01/2022
# Data de atualização:			01/01/2022
# Versão:						0.01
# Testado e homologado para a versão do Ubuntu Server 20.04.x LTS x64
# Testado e homologado para a versão do Apache2 v2.4.x
#
# Configuração do Unset do Home do Apache2
unset HOME
#
# Configurações para suportar várias instâncias do Apache2
if [ "${APACHE_CONFDIR##/etc/apache2-}" != "${APACHE_CONFDIR}" ] ; then
	SUFFIX="-${APACHE_CONFDIR##/etc/apache2-}"
else
	SUFFIX=
fi
#
# Configurações das variáveis de ambiente utilizadas pelo Apache2
export APACHE_RUN_USER=www-data
export APACHE_RUN_GROUP=www-data
export APACHE_PID_FILE=/var/run/apache2$SUFFIX/apache2.pid
export APACHE_RUN_DIR=/var/run/apache2$SUFFIX
export APACHE_LOCK_DIR=/var/lock/apache2$SUFFIX
export APACHE_LOG_DIR=/var/log/apache2$SUFFIX
#
# Configuração da localidade usada por alguns módulos como mod_dav
# OBSERVAÇÃO: configurações utilizadas pelo Nextcloud de Locale
export LANG=C
. /etc/default/locale
export LANG
#
# Configurações padrão do Apache2 Envvars, recomendado não alterar os valores
#export APACHE_LYNX='www-browser -dump'
#APACHE_ULIMIT_MAX_FILES='ulimit -n 65536'
#export APACHE_ARGUMENTS=''
#export APACHE2_MAINTSCRIPT_DEBUG=1
