#!/bin/bash
# Autor:						Jensy Gregorio Gomez
# YouTube:						youtube.com/systech
# Instagram:					https://www.instagram.com/systech5/?hl=pt-br
# Github:						https://github.com/vaasystech-brz
# Data de criação:				01/01/2022
# Data de atualização:			01/01/2022
# Versão:						0.01
# Testado e homologado para a versão do Ubuntu Server 20.04.x LTS x64
# Kernel >= 4.15.x
# Testado e homologado para a versão do TFTP-HPA v5.2.x e PXE Syslinux v

default vesamenu.c32
prompt 0
timeout 300

label puppy
  menu label ^Live-CD do Puppy Linux via PXE
  kernel puppy/vmlinuz
  append initrd=puppy/initrd.gz