#!/bin/bash
# Autor:						Jensy Gregorio Gomez
# YouTube:						youtube.com/systech
# Instagram:					https://www.instagram.com/systech5/?hl=pt-br
# Github:						https://github.com/vaasystech-brz
# Data de criação:				01/01/2022
# Data de atualização:			01/01/2022
# Versão:						0.01
# Testado e homologado para a versão do Ubuntu Server 20.04.x LTS x64
#
# Configurações Globais do Prometheus
global:
  scrape_interval: 15s
  evaluation_interval: 15s
#
# Configuração do Sistema de Gerenciamento de Alertas do Prometheus
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093
#
# Configuração do Carregamento das Regras Periódica do Prometheus 
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"
#
# Configurações do Serviço do Prometheus (alterado a Porta para 9091 para não entrar
# em conflito com o serviço do OpenFire, porta padrão do Prometheus 9090)
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9091"]