#!/bin/bash
# Autor:						Jensy Gregorio Gomez
# YouTube:						youtube.com/systech
# Instagram:					https://www.instagram.com/systech5/?hl=pt-br
# Github:						https://github.com/vaasystech-brz
# Data de criação:				01/01/2022
# Data de atualização:			01/01/2022
# Versão:						0.01
# Testado e homologado para a versão do Ubuntu Server 20.04.x LTS x64
# Testado e homologado para a versão do Nginx v.x
#
#Configuração do Virtual Host padrão do Nginx na porta 80
server {
	#	
	#Configuração da Porta de acesso ao Servidor HTTP do Nginx
	listen 80 default_server;
	listen [::]:80 default_server;
	#
	#Pasta raiz da hospedagem
	root /var/www/html;
	#
	#Arquivos de inicialização de páginas Web
	index index.html index.htm index.nginx-debian.html index.php;
	#
	#Configuração do Nome do Servidor do Nginx
	server_name _;
	#
	location / {
		try_files $uri $uri/ =404;
	}
	#
	#Configuração do suporte ao PHP no Nginx
	location ~ \.php$ {
		include snippets/fastcgi-php.conf;
		fastcgi_pass unix:/var/run/php/php7.2-fpm.sock;
	}
}
