#!/bin/bash
# Autor:						Jensy Gregorio Gomez
# YouTube:						youtube.com/systech
# Instagram:					https://www.instagram.com/systech5/?hl=pt-br
# Github:						https://github.com/vaasystech-brz
# Data de criação:				01/01/2022
# Data de atualização:			01/01/2022
# Versão:						0.01
# Testado e homologado para a versão do Ubuntu Server 20.04.x LTS x64
# Testado e homologado para a versão do Tomcat 9.0.x, OpenJDK 11.x, OpenJRE 11.x
# Testado e homologado para a versão do Apache Guacamole Server 1.3.x e Cliente 1.3.x

# Parâmetros de inicialização padrão do JAVA do Tomcat9 
JAVA_OPTS="-Djava.awt.headless=true -XX:+UseG1GC"

# Configuração do Webapp do Apache Guacamole Server e Client
GUACAMOLE_HOME=/etc/guacamole